project:
  type: website
  output-dir: docs
  resources: .nojekyll
  render:
    - index.qmd
    - project.qmd
    - paper.qmd
    - test-summaries/README.md
    - test-summaries/*.md

format:
  html:
    # Theme: cosmo | flatly | litera | lumen | lux | minty | pulse | sandstone | united | yeti | zephyr | darkly | solar | slate | ...
    theme: cosmo
    fontsize: 0.9em

website:
  title: "Coset"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Documentation
      - href: paper.qmd
        text: Publication
      - href: test-summaries/README.html
        text: Test Docs
    right:
      - icon: github
        href: https://github.com/coset/coset
        text: Source
